version: "3.9"

services:
  web-server:
    build:
      context: ./webserver
    container_name: tree-table-demo-web-server
    ports:
      - 80:80

  database:
    build:
      context: ./database
      dockerfile: Dockerfile.test
    container_name: tree-table-demo-database
    ports:
      - 3306:3306

  webapi:
    build:
      context: ./webapi
      dockerfile: Dockerfile.develop
    container_name: tree-table-demo-webapi
    stop_signal: SIGKILL
    ports:
      - 8000:8000

networks:
  default:
    name: tree-table-demo

