version: "3.9"

services:
  web-server:
    build:
      context: ./interface
    container_name: tree-table-demo-web-server
    ports:
      - 80:80

  database:
    build:
      context: ./database
      args:
        MYSQL_ROOT_PASSWORD: tree-table-demo-database-mysql-root-password
        MYSQL_DATABASE: tree_table_demo
    container_name: tree-table-demo-database
    ports:
      - 3306:3306

networks:
  default:
    name: tree-table-demo

