FROM mysql:8.0.32-debian as builder

ENV MYSQL_ROOT_PASSWORD=tree-table-demo-database-mysql-root-password
ENV MYSQL_DATABASE=tree_table_demo

COPY minimal_memory.conf /etc/mysql/conf.d/
COPY create_tables.sql /docker-entrypoint-initdb.d/

COPY insert_test_data.sql /docker-entrypoint-initdb.d

RUN ["sed", "-i", "s/exec \"$@\"/echo \"not running $@\"/", "/usr/local/bin/docker-entrypoint.sh"]

RUN docker-entrypoint.sh mysqld

FROM mysql:8.0.32-debian

COPY --from=builder /var/lib/mysql /var/lib/mysql
COPY minimal_memory.conf /etc/mysql/conf.d

