FROM python:3.12-rc-bullseye

WORKDIR /test

RUN pip install flask flask-cors pymysql cryptography dataclasses_json

COPY webapi_server.py webapi_server_helper.py unittest_webapi_server.py /test

CMD python3 unittest_webapi_server.py
