version: "3.9"

services:
  database:
    build:
      context: ../database
      dockerfile: Dockerfile.test
    container_name: tree-table-demo-webapi-test-database
    cap_add:
      - SYS_NICE
    healthcheck:
      #test: ["CMD", "mysql", "-u", "root", "-ptree-table-demo-database-mysql-root-password", "-e", '"select 1;"']
      test: ["CMD", "mysqladmin", "ping"]
      interval: 1s
      retries: 10
      start_period: 2s

  webapi-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: tree-table-demo-webapi-test
    environment:
      DATABASE_HOST_NAME: database
    depends_on:
      database:
        condition: service_healthy

networks:
  default:
    name: tree-table-demo-webapi-test-network

