FROM python:3.11-bullseye

WORKDIR /check

# development libraries
RUN pip install mypy \
  types-PyMySQL types-Flask types-Flask-Cors

# runtime libraries
RUN pip install flask flask-cors flask-login pymysql dataclasses_json

COPY *.py /check

CMD mypy webapi_server.py unittest_webapi_server.py

