# referenced from https://qiita.com/sounisi5011/items/eba7cf3ed65973e6edb2
name: Auto Approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  approve:
    if:
      github.event.pull_request.user.login == github.repository_owner
      && ! github.event.pull_requests.draft
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmrr/auto-aprove-action@v3
